name: sponsor ❤️
on: [issues, pull_request]

jobs:
  sponsor:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2

      - name: ❤️ sponsor 
        uses: devlooped/actions-sponsor@main
        with:
          token: ${{ secrets.GH_TOKEN }}
