name: sponsors
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kzu/is-sponsor-label-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}