# Runs on new issues/PRs and applies sponsor labels

name: sponsors
on:
  pull_request:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, edited, reopened, transferred]

defaults:
  run:
    shell: pwsh

jobs:
  label-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: 🔽 gh 
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install gh

      - name: 💛 sponsors
        run: ./.github/workflows/sponsors.ps1
        env:
          GH_TOKEN: ${{ secrets.DEVLOOPED_TOKEN }}