# Runs on new issues/PRs and applies sponsor labels

name: sponsors
on:
  pull_request:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, edited, reopened, transferred]

jobs:
  sponsors:
    runs-on: ubuntu-20.04
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2

      - name: 🔽 gh 
        run: brew install gh

      - name: 💛 sponsors
        shell: pwsh
        run: ./.github/workflows/sponsors.ps1
        env:
          GH_TOKEN: ${{ secrets.DEVLOOPED_TOKEN }}